from . import test_property_common
from . import test_property_inventory_crud
from . import test_property_inventory_dates
from . import test_property_inventory_cron
from . import test_suggestion_crud
from . import test_suggestion_counts
from . import test_suggestion_whatsapp
from . import test_suggestion_feedback
from . import test_suggestion_cron
from . import test_suggestion_dates
from . import test_integration