name: Deploy Odoo to GCP VM
# This pipeline runs on every push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VM
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VM and deploy
        uses: appleboy/ssh-action@v1.0.3  # Pin to a stable version
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22  # Explicitly set for clarity
          timeout: 120s  # Increased to handle latency and VM delays
          command_timeout: 15m  # Sufficient for Docker build/restart
          debug: true  # Enable verbose logging for troubleshooting
          script: |
            set -e  # Exit on any error
            echo "Connected as $(whoami)"
            df -h  # Check disk space
            free -m  # Check memory
            cd ~/odoo-project || { echo "Error: odoo-project directory not found"; exit 1; }
            echo ">>> Pulling latest changes from Git..."
            git pull origin main || { echo "Error: Git pull failed"; exit 1; }
            echo ">>> Rebuilding Odoo image..."
            docker-compose build odoo || { echo "Error: Docker build failed"; exit 1; }
            echo ">>> Restarting the Odoo Service..."
            docker-compose up -d --force-recreate odoo || { echo "Error: Docker restart failed"; exit 1; }
            echo ">>> Deployment Finished Successfully!"
